import "./globals.css";

import RootProvider from "./RootProvider";
import { AuthProvider } from "@/contexts/AuthContext";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import { Layout } from "@/components/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />

        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="min-h-full flex flex-col font-sans">
        <RootProvider>
          <AuthProvider>
            <ThemeProvider>
              <Layout>{children}</Layout>
            </ThemeProvider>
          </AuthProvider>
        </RootProvider>
      </body>
    </html>
  );
}
